### ISSUE TITLE
IE javascript with "=>" not supported in IE

### ISSUE THREAD

**Issue by VikingIT** [adyen-examples/adyen-dotnet-online-payments#1]
Manged to get this example running after a few tries. Following the instruction resulted in an exception when getting the payment methods. Looks like the instructions are for MAC and not windows?

The javascript file adyenImplementation.js makes frequent use of "=>" which is not supported by IE. See https://stackoverflow.com/questions/44437497/syntax-error-using-in-ie.

**Comment by deepu105** [comment]
Thanks for reporting this. Sorry for the inconvenience, the samples are written with evergreen browsers in mind and thats why IE is not supported as Microsoft is dropping support of IE next year. You can replace the arrow functions with normal functions if you want to use it in IE.

I'll update the Readme with windows specific instructions

**Comment by VikingIT** [comment]
Sorry, my mistake there. 
I wouldn't have bothered if it was only IE but it failed in Edge as well, I'm still thinking of all Microsoft browsers as IE...
I checked again and it does work in Edge so it must have been something else.

**Comment by deepu105** [comment]
No worries.
