### ISSUE TITLE
Add Swish to the list of available payment methods in the demo

### ISSUE THREAD

**Issue by jlengrand** [adyen-examples/adyen-dotnet-online-payments#12]

**Comment by jlengrand** [comment]
See #7

**Comment by jlengrand** [comment]
For Swish, the country needs to be Sweden (SE) and the currency SEK.

In this example, I removed iDEAL which is more Dutch centric and replaced it by Swish.

You can find the complete documentation for Swish in a component [here](https://docs.adyen.com/payment-methods/swish/web-component).

**Comment by jonekdahl** [comment]
That looks easy enough. I thought we needed to [confirm an additional action](https://docs.adyen.com/online-payments/web-components/advanced-use-cases/additional-actions) after the QR code was scanned, but perhaps that part is optional?

**Comment by jlengrand** [comment]
From the documentation I linked above and the example I made, it looks like Swish doesn't require it!
