### ISSUE TITLE
Billing information not showing on card details

### ISSUE THREAD

**Issue by gpiramide** [adyen-examples/adyen-dotnet-online-payments#18]
Hi trying this code it runs ok, but the billing information not showing, what seems to be the problem.

Thankyou
![adyen](https://user-images.githubusercontent.com/12013266/159113659-393c63e6-b90f-4e14-b76f-104108e00002.JPG)
![Uploading adyen.JPG…]()

**Comment by gpiramide** [comment]
Thank you for your reply julien, i tried it on live on my site but I can't seem to get this up and running it give me an error.
it will display the page correctly but when i hit the check out button give me an error. already added the url in adyen allow site,  thank you. pls help,

![adyen](https://user-images.githubusercontent.com/12013266/159420530-534eb408-bed5-4021-934d-9ca8e11f5dac.png)

**Comment by jlengrand** [comment]
Closing because stale
