### ISSUE TITLE
Unable to checkout

### ISSUE THREAD

**Issue by knguyengit** [adyen-examples/adyen-dotnet-online-payments#26]
I've pulled the latest stable. I also set the following hard-coded from the values I got off my test Adyen account.

ADYEN_API_KEY
ADYEN_MERCHANT
ADYEN_CLIENT_KEY

When I start the server (dotnet run) and go to https://localhost:5001, Chrome changes it to not secure. I chose Drop-in and after clicking "Continue to Checkout", it fails with the error below

![image](https://user-images.githubusercontent.com/108461877/176650670-82062038-83b3-4bac-9618-e2e6fae0dc08.png)

Am I missing something?

**Comment by knguyengit** [comment]
@deepu105 @jlengrand @gcatanese Please help!

**Comment by Kwok-he-Chu** [comment]
Hi @knguyengit Happy to help!

Please go to your ca-test environment, under your merchantAccount > Developers (in the left-tab-menu) > API credentials > Find your ws_00000 user. In the "Allowed origins"-section, you can add your allowed origins. In your case, please add "https://localhost:5001"

**Comment by gcatanese** [comment]
@knguyengit Something to consider is that the en variable is now called `ADYEN_MERCHANT_ACCOUNT`, this is a very recent change (yesterday?) so it might not be a problem for you, but if you clone/pull again please make sure to use `ADYEN_MERCHANT_ACCOUNT` (instead of `ADYEN_MERCHANT`)

**Comment by knguyengit** [comment]
Thank you for your responses. Once I added it to the allow origins it worked. Thank you!
