### ISSUE TITLE
Question: how does one pass a unique order ID using Drop-in?

### ISSUE THREAD

**Issue by MPV65** [adyen-examples/adyen-dotnet-online-payments#3]
This may be categorized as either a question or suggestion for development rather than an issue. 

It would be very useful to know how to adapt the code in this repository so that one can send a unique order ID to the InitiatePayment API endpoint from the client side.

**Comment by deepu105** [comment]
Can you please clarify the question? This example already sents a unique order id to the payment endpoints

**Comment by deepu105** [comment]
closing as there is no further info
