### ISSUE TITLE
Payment is refused or cancelled

### ISSUE THREAD

**Issue by dariusz-wozniak** [adyen-examples/adyen-dotnet-online-payments#39]
When I choose either the _Drop-in_ or _Card_ option AND when I enter one of the [test card numbers](https://docs.adyen.com/development-resources/testing/test-card-numbers) for Mastercard or Visa, I get either `Cancelled` or `Refused` value of `resultCode`.

Example of console log:

```
Navigated to https://localhost:5001/
Navigated to https://localhost:5001/preview/dropin
Navigated to https://localhost:5001/checkout/dropin
adyenImplementation.js?v=DeHm8zJSTQb72kADPbcdsCCrt-TWxnIuW8p-8zoqdq0:66 onPaymentCompleted
adyenImplementation.js?v=DeHm8zJSTQb72kADPbcdsCCrt-TWxnIuW8p-8zoqdq0:67 {resultCode: 'Refused', sessionData: '[REMOVED]'} r {_id: 'dropin-[GUID]', props: {…}, state: {…}, _node: div#payment.payment, _component: {…}, …}
```

I have added `https://localhost:5001` in allowed origins under Client settings in API Credential configuration.

Any ideas about what is wrong?

**Comment by Kwok-he-Chu** [comment]
Which card number did you enter?

**Comment by dariusz-wozniak** [comment]
@Kwok-he-Chu :

For example, `4988 4388 4388 4305`.

![image](https://user-images.githubusercontent.com/5969160/190113308-7bf37dee-c212-4c58-bf10-24635a7aa5a3.png)

It results with `Refused` payment.

**Comment by Kwok-he-Chu** [comment]
@dariusz-wozniak Please check the risk-profile section in your ca-test environment. You should be able to see the transactions that have failed (look up your pspReference number and see how the risk score is calculated). If the risk score is too high we refuse the payment. Various factors could lead up to a "Refused"-payment.

**Comment by dariusz-wozniak** [comment]
@Kwok-he-Chu : Yes, that is correct. I updated risk settings and it works fine now. Thank you!
