### ISSUE TITLE
Updating to use TypeScript and type definitions from adyen-web npm package

### ISSUE THREAD

**Issue by RyanONeill1970** [adyen-examples/adyen-dotnet-online-payments#56]
I'm working on changing the adyenImplementation.js in checkout-example to use TypeScript so that it is easier to update to the latest version and let the TypeScript compiler catch the breaking changes.

I've tried the steps below but it does not look like the adyen type definition files can be used by this project as they seem to depend on a module loader being used in the browser. **Is there an easy way to use the TypeScript definition files from the Adyen npm package in this project?**

My fork of the project with the changes below is at https://github.com/RyanONeill1970/adyen-dotnet-online-payments .

1. I've copied adyenImplementation.js to /scripts/adyenImplementation.ts, it will overwrite the .js when compiled.
2. This shows that TypeScript is unaware of AdyenCheckout. To fix this I've added a package.json and set dependencies to include "@adyen/adyen-web": "5.31.1" . This downloads the latest version of the Adyen JS library into node_modules.
3. Changed callServer("/api/sessions") to callServer("/api/sessions", null) to explicitly pass in the unused parameter. Fixes a TypeScript parameter error.
4. Added a tsconfig.json file and set the js target to be es2017, this fixes the error caused by the usage of async.
5. In the tsconfig.json file, set moduleResolution to node which ensures the Adyen npm package is built and found.
6. In the tsconfig.json file, set outDir to "wwwroot/js" to output the compiled adyen-implementation.js.
7. Add a TypeScript definition reference of '/// <reference path="../node_modules/@adyen/adyen-web/dist/types/index.d.ts" />
' to the root of adyenImplementation.ts to ensure it finds the type definitions in the Adyen npm package. This should not be needed and is just for troubleshooting.

The TypeScript compiler does not pick up the type definitions from the the npm package, it seems ignore the file as it contains imports and exports. This results in a failed compile.

Original index.d.ts from the Adyen npm package;

    import { CoreOptions } from './core/types';
    import Checkout from './core';
    declare function AdyenCheckout(props: CoreOptions): Promise<Checkout>;
    export default AdyenCheckout;

If I replace the above file contents with the following, it compiles;

    declare var AdyenCheckout: any;

This proves that TypeScript can find the file, but the contents don't look like a traditional type definition file (I think), so it is not used as such.

This means means I don't get any type definitions. For example, TypeScript now ignores the error with AdyenCheckout now being async in the latest version.

**Comment by RyanONeill1970** [comment]
I've solved this now and have a TypeScript version, with the Type Definitions from the latest copy of Adyen importing via an npm package and using the latest (as of now) live version of the package via a script reference.

If you'd like me to do a pull request for this (from [this repo](https://github.com/RyanONeill1970/adyen-dotnet-online-payments)), I'm more than happy to. Otherwise, please just close this.

**Comment by Kwok-he-Chu** [comment]
I've taken a look and I'm trying to understand the changes that you've made. I wasn't expecting the embedded script to be used together with the npm version of Adyen-Web. 

We expect our merchants to use the npm version [https://docs.adyen.com/online-payments/web-components#get-adyen-web](https://docs.adyen.com/online-payments/web-components#get-adyen-web) when using TypeScript. We'd like to understand why this is not a solution in your use-case. Can you use the [embedded script](https://github.com/adyen-examples/adyen-dotnet-online-payments/blob/main/checkout-example/Views/Shared/_Layout.cshtml#L10,L20) only?

**Comment by RyanONeill1970** [comment]
Thanks for replying. I'd like to use the NPM version as well, but as I understand it, we'll need to implement a module loader on the client or transpile the modules into a single script file and then load that script file via a script tag (to avoid requiring a module loader).

Our current codebase does not use a module loader and we don't have a transpiler in the build process. It is something that I'd like to address but we're coming from an older JS / TS setup that is not module based. Hence the inclusion of Adyen via a script tag.

Does that make sense? I may have it wrong, but in essence we don't want a module loader on the client as we'd like to load scripts via the script tags and have control over them. I think transpilation is where I want to go so we can use modules and not depend on a loader, I need to find some proper documentation on this though.

**Comment by Kwok-he-Chu** [comment]
That makes sense. I've checked-in with the [Adyen-web](https://github.com/adyen/adyen-web) team and unfortunately, we only support TypeScript when using a module loader. This seems like the most common use case. Without the module loader, the only possibility is to use the embedded script which is written in javascript. 

Supporting your specific use-case is not something we're currently looking into, but it seems like you have a workaround for it. I'll close this issue if there are no further questions 👍 Thank you for reaching out to us!
