### ISSUE TITLE
Card number cannot be entered

### ISSUE THREAD

**Issue by yuan718935659** [adyen-examples/adyen-dotnet-online-payments#6]
When I use the test case to run, it can run normally, but when I get to the payment page, I can’t pay, please see the screenshot：
 Drop-in =>Continue to checkout =>Credit or debit card
![image](https://user-images.githubusercontent.com/14085129/141096499-4d6ca451-f672-4ca7-a160-c5b6f4e20fc3.png)

**Comment by yuan718935659** [comment]
https://github.com/adyen-examples/adyen-react-online-payments/issues/5

**Comment by jlengrand** [comment]
Glad you found a solution, Let me know if you need anything else!

**Comment by yuan718935659** [comment]
谢谢您的来信 我已收到。。。
