### ISSUE TITLE
"status":401

### ISSUE THREAD

**Issue by pineportal** [adyen-examples/adyen-dotnet-online-payments#67]
hello.
I get the following error during the local test
 adyen_dotnet_subscription_example.Clients.RecurringClient[0]
      Request for Payments failed::
{"status":401,"errorCode":"000","message":"HTTP Status Response - Unauthorized","errorType":"security"}

![image](https://user-images.githubusercontent.com/31403448/224320400-2e52fb15-1162-4a7a-8cbf-9700ed570aac.png)

How to fix it?

**Comment by Kwok-he-Chu** [comment]
@pineportal Hey, I just wanted to check in and see if you're still having the same issue. If not, feel free to close the issue👍

**Comment by Kwok-he-Chu** [comment]
Feel free to open up a new issue if it still persists.
