### ISSUE TITLE
Support for API version 68

### ISSUE THREAD

**Issue by jonekdahl** [adyen-examples/adyen-dotnet-online-payments#7]
Hi,

It's great that a resource like this repo exists, that shows how Adyen can be implemented in dotnet. We're currently implementing version 68 of the API. This repo currently shows how to implement API version 67, so it is missing the session creation part.

The Adyen dotnet library has support for API version 68 since [version 8.0.0](https://github.com/Adyen/adyen-dotnet-api-library/releases/tag/8.0.0) that was released a couple of months ago. Will this repo be updated to show how to work with payment sessions and other potential changes in API version 68?

Thanks!

**Comment by jlengrand** [comment]
Hey @jonekdahl . You're right, we're lagging behind on some of the examples. Let me put dotnet on top of the list.

**Comment by jonekdahl** [comment]
Sounds great!

**Comment by jlengrand** [comment]
Hey @jonekdahl! 

You can find a very first version in https://github.com/adyen-examples/adyen-dotnet-online-payments/pull/8. It was my first time doing dotnet so please excuse the possibly non idiomatic code. 

It should get reviewed in the coming days before getting merged. 

Feel free to let me know if you're missing anything!

**Comment by jonekdahl** [comment]
Hey @jlengrand. I don't think anything is missing. We're going to use the Swish payment method so I wouldn't mind seeing that implemented in this repo but I could just as well open another issue for that.

**Comment by jlengrand** [comment]
Hey @jonekdahl . I'm back from vacations today :). Happy new year.

In this PR, we are missing an important feature. As of V68 and using sessions endpoints, the usage of web hooks is required to get the final status of your payments, while it was a strong recommendation in the past.

I will add that feature in the coming days. 

I'll create another issue regarding Swish. Do you folks need that example urgently?

**Comment by jonekdahl** [comment]
Hi @jlengrand! I hope you had a nice vacation.

The webhook seems like a crucial part if it is now required.

The Swish example would be nice to have, but I think we could figure it out just by reading the docs so I wouldn't say it's urgent.

**Comment by jonekdahl** [comment]
Hi @jlengrand. Is there anything more you plan to do before support for API version 68 is complete?

**Comment by jlengrand** [comment]
Hey @jonekdahl . Webhooks are part of the sample now (https://github.com/adyen-examples/adyen-dotnet-online-payments/blob/main/Controllers/WebhookController.cs), so support is complete! 

Thanks for the reminder, will be closing this now
