### ISSUE TITLE
Bin Code info

### ISSUE THREAD

**Issue by drawtsae** [adyen-examples/adyen-dotnet-online-payments#98]
Any way to get bincode before payment and after payment

**Comment by Kwok-he-Chu** [comment]
Hi @drawtsae, 

If you have business logic based on BIN values, you can use the BIN fields from the API response to get the information you need. You can simply enable this in the `Customer Area` -> `Developers` -> 'Additional Data' -> 'Card'

Alternatively, you can check against the BIN ranges from card networks, if you handle raw card data -> You'll need to be [fully PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide) for this. If you're not fully PCI compliant, use one of our [client-side solutions](https://docs.adyen.com/payment-methods/cards#how-do-you-want-to-integrate) or make a [custom card integration](https://docs.adyen.com/payment-methods/cards/custom-card-integration) instead.

Let me know if that helped move your integration forward!

[Documentation source](https://docs.adyen.com/get-started-with-adyen/payment-glossary/#bank-identification-number-bin)

**Comment by Kwok-he-Chu** [comment]
Screenshot below:
<img width="1011" alt="Screenshot 2023-09-04 at 16 12 43" src="https://github.com/adyen-examples/adyen-dotnet-online-payments/assets/105217051/c6b7cbdc-da59-4b1b-a978-a8c81c6d5fbc">
